version: '3.8'

services:
  encriptacion-api:
    image: christianpaul24/backendcom
    ports:
      - "5000:5000"
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            capabilities: [gpu]

  encriptacion-web:
    image: christianpaul24/fronendcom
    ports:
      - "8083:80"
    depends_on:
      - encriptacion-api